[workspace]
authors = ["eternal-flame-AD <yume@yumechi.jp>"]
channels = ["conda-forge"]
name = "plots"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-tidyverse = ">=2.0.0,<3"
r = ">=4.4,<4.5"
r-cowplot = ">=1.1.3,<2"
r-patchwork = ">=1.3.0,<2"
